name: better-goals

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BETTER_GOALS_S3: "better-goals-cdn"
      LAMBDA_ROLE: "arn:aws:iam::819351115289:role/iam_for_lambda"
      LAMBDA_FUNCTION_NAME: "better-goals"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build

